### ISSUE TITLE
Задается отрицательный начальный баланс при создании кредитного счета 

### ISSUE THREAD

**Issue by IrinaRakova** [IrinaRakova/javaqa-team-diplom-2#1]
# Описание
При создании нового объекта кредитного счета параметр начальный баланс счета `initialBalance` можно задать отрицательным числом, при этом не выводится исключение вида `IllegalArgumentExeption`.

# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L28

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount 
3. Выставить значение начального балансом счета `initialBalance` равным «-10000»
4. Выставить значение кредитного лимита `creditLimit` равным «100000»
5. Выставить значение ставки кредитования `rate` равным «10»
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод исключения вида `IllegalArgumentExeption` с сообщением «Начальный баланс счета не может быть отрицательным, а у вас: -10000».
*Фактический результат:* Начальный баланс счета `initialBalance` назначился равным «-10000».

# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L50-L61

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/144940283/d74e55dd-54cc-4ce1-9f16-75fd26e51fe2)

# Окружение
* **Операционная система:** Microsoft Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.2.2
* **Java:** OpenJDK 11

**Comment by SLiliya** [comment]
В метод `CreditAccount` добавлено новое условие, тест shouldBeIllegalArgumentExceptionForNegativeInitialBalance проходит без ошибок.
# Локация изменений
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L33-L37
