### ISSUE TITLE
Возможность ввода на сберегательном счете отрицательной суммы минимального баланса 

### ISSUE THREAD

**Issue by SLiliya** [IrinaRakova/javaqa-team-diplom-2#12]
# Описание
Если на сберегательном счете минимальный баланс отрицательный, то не отображается исключение вида `IllegalArgumentException`.
# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L18) в IDEA
2. Выставить значение переменной `initialBalance` (начальный баланс) 1 тыс. руб. 
3. Выставить значение переменной `minBalance` (минимальный баланс)  -1 тыс. руб.
4. Выставить значение переменной `maxBalance` (максимальный баланс) 10 тыс. руб. 
5. Выставить значение переменной `rate` (процентная ставка) 2%  
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит и завершается исключением вида `IllegalArgumentException`
*Фактический результат:* тест не проходит, исключение вида `IllegalArgumentException` не обнаружено
# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L20-L31

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/145185698/4cdfc7ee-04ec-4aac-85ed-2423eea4c230)

# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.2.5 (Community Edition)
* **Java:** OpenJDK11

**Comment by IrinaRakova** [comment]
**Баг исправлен**
Исключена возможность ввода на сберегательном счете отрицательной суммы минимального баланса

**Локация исправленного места**
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L34-L38
