### ISSUE TITLE
Возможность ввода суммы начального баланса на сберегательном счете больше суммы максимального баланса 

### ISSUE THREAD

**Issue by SLiliya** [IrinaRakova/javaqa-team-diplom-2#14]
# Описание
Если на сберегательном счете сумма начального баланса больше максимального баланса, то не отображается исключение вида `IllegalArgumentException`.
# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L18) в IDEA
2. Выставить значение переменной `initialBalance` (начальный баланс) 10 001 руб. 
3. Выставить значение переменной `minBalance` (минимальный баланс)  - 0 руб.
4. Выставить значение переменной `maxBalance` (максимальный баланс) 10 тыс. руб. 
5. Выставить значение переменной `rate` (процентная ставка) 2%  
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* тест проходит и завершается исключением вида `IllegalArgumentException`
*Фактический результат:* тест не проходит, исключение вида `IllegalArgumentException` не обнаружено
# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L45-L55

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/145185698/e533b160-de5a-42f4-a2e1-f92d510d7912)

# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.2.5 (Community Edition)
* **Java:** OpenJDK11

**Comment by IrinaRakova** [comment]
**Баг исправлен**
Исключена возможность ввода суммы начального баланса на сберегательном счете больше суммы максимального баланса 

**Локация исправленного места**
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L48
