### ISSUE TITLE
Задается отрицательный кредитный лимит при создании кредитного счета 

### ISSUE THREAD

**Issue by IrinaRakova** [IrinaRakova/javaqa-team-diplom-2#2]
# Описание
При создании нового объекта кредитного счета параметр кредитный лимит `creditLimit` можно задать отрицательным числом, при этом не выводится исключение вида `IllegalArgumentExeption`.

# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L28

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса `CreditAccount` 
3. Выставить значение начального балансом счета `initialBalance` равным «10000»
4. Выставить значение кредитного лимита `creditLimit` равным «-100000»
5. Выставить значение ставки кредитования `rate` равным «10»
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод исключения вида `IllegalArgumentExeption` с сообщением «Кредитный лимит счета не может быть отрицательным, а у вас: -100000».
*Фактический результат:* Кредитный лимит счета `creditLimit` назначился равным «-100000».

# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L92-L103

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/144940283/c758e1ca-0c94-4568-bd9d-626d31b6eed3)

# Окружение
* **Операционная система:** Microsoft Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.2.2
* **Java:** OpenJDK 11

**Comment by SLiliya** [comment]
В метод CreditAccount добавлено новое условие, тест shouldBeIllegalArgumentExceptionForNegativeCreditLimit проходит без ошибок.
# Локация изменений
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L28-L32
