### ISSUE TITLE
Не задается нулевая ставка кредитования при создании кредитного счета 

### ISSUE THREAD

**Issue by IrinaRakova** [IrinaRakova/javaqa-team-diplom-2#3]
# Описание
При создании нового объекта кредитного счета параметр ставка кредитования `rate` не задается равным 0, при этом выводится исключение вида `IllegalArgumentExeption`.

# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L24

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса `CreditAccount` 
3. Выставить значение начального балансом счета `initialBalance` равным «10000»
4. Выставить значение кредитного лимита `creditLimit` равным «100000»
5. Выставить значение ставки кредитования `rate` равным «0»
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат:* Ставка кредитования `rate` назначилась равной «0».
*Фактический результат:* Вывод исключения вида `IllegalArgumentExeption` с сообщением «Накопительная ставка не может быть отрицательным, а у вас: 0».

# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L119-L131

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/144940283/18ec757d-2251-4a02-91b1-ebecba2816d1)

# Окружение
* **Операционная система:** Microsoft Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.2.2
* **Java:** OpenJDK 11

**Comment by SLiliya** [comment]
В методе `CreditAccount` изменено условие, тест shouldBeZeroRate проходит без ошибок.
# Локация изменений
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L21-L27
