### ISSUE TITLE
Баланс становится равным сумме покупки после выполнения операции пополнения

### ISSUE THREAD

**Issue by IrinaRakova** [IrinaRakova/javaqa-team-diplom-2#5]
# Описание
После выполнения операции пополнения `add()` баланс `balance` становится равным значению суммы покупки `amount`.

# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса `CreditAccount`
3. Выставить значение начального балансом счета `initialBalance` равным «10000»
4. Выставить значение кредитного лимита `creditLimit` равным «100000»
5. Выставить значение ставки кредитования `rate` равным «10»
6. Вызвать метод пополнения `add()`, задав значение суммы покупки `amount` равным «2000»
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс увеличился на сумму покупки и составляет «12000».
*Фактический результат:* Баланс равен сумме покупки и составляет «2000».

# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/8b0e87e4fa95a2c29570540bf9c550b6a6f2e934/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L233-L247

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/144940283/27e30484-7dc2-4196-9470-62f4bcaa819d)

# Окружение
* **Операционная система:** Microsoft Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.2.2
* **Java:** OpenJDK 11

**Comment by SLiliya** [comment]
В методе `add` изменено условие, тест shouldAddAmountToBalance проходит без ошибок.
# Локация изменений
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L85
