### ISSUE TITLE
Ставка кредитования начисляется на положительный остаток на счете при выполнении операции прогноза процентов за год

### ISSUE THREAD

**Issue by IrinaRakova** [IrinaRakova/javaqa-team-diplom-2#7]
# Описание
При выполнении операции прогноза процентов за год `yearChange()` ставка кредитования `rate` начисляется на положительный остаток на счете.

# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L84

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса `CreditAccount` 
3. Выставить значение начального балансом счета `initialBalance` равным «10000»
4. Выставить значение кредитного лимита `creditLimit` равным «100000»
5. Выставить значение ставки кредитования `rate` равным «15»
6. Задать значение баланса `balance` равным «10000»
7. Вызвать метода прогноза процентов за год `yearChange()` 
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Сумма процентов на отрицательный баланс счета равна «0».
*Фактический результат:*  Сумма процентов на отрицательный баланс счета равна «1500».

# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/5d3f757326ef59849150f690d88dd666fe5697a1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L307-L320

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/144940283/2c49279a-4666-40c1-a749-52fdd6662e99)

# Окружение
* **Операционная система:** Microsoft Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.2.2
* **Java:** OpenJDK 11

**Comment by SLiliya** [comment]
Добавлено условие в метод `yearChange`, тест shouldNotCalculatePercentOnPositiveBalance проходит без ошибок.
# Локация изменений
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L99-L103
