### ISSUE TITLE
Баланс сберегательного счета становится равен сумме пополнения счета при внесении денежных средств

### ISSUE THREAD

**Issue by SLiliya** [IrinaRakova/javaqa-team-diplom-2#8]
# Описание
Если внести на сберегательный счет денежные средства, то баланс становится равен сумме пополнения.
# Локация дефекта
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78
# Шаги воспроизведения

1. Открыть [код программы](https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L45-L55) в IDEA
2. Выставить значение переменной `initialBalance` (начальный баланс) 2 тыс. руб. 
3. Выставить значение переменной `minBalance` (минимальный баланс)1 тыс. руб. 
4. Выставить значение переменной `maxBalance` (максимальный баланс)10 тыс. руб. 
5. Выставить значение переменной `rate` (процентная ставка) 5% 
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат:* сумма на балансе сберегательного счета равна 5 тыс. руб.
*Фактический результат:* сумма на балансе сберегательного счета равна 3 тыс. руб.
# Локация теста, проверяющего дефект
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/6c675e83fc1a5e90804bb01feff84b0859df21e0/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L106-L117

# Скриншот
![image](https://github.com/IrinaRakova/javaqa-team-diplom-2/assets/145185698/91082948-d55c-4b97-a265-3dfbcca559f4)

# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.2.5 (Community Edition)
* **Java:** OpenJDK11

**Comment by IrinaRakova** [comment]
**Баг исправлен**
Баланс сберегательного счета после воспроизведения операции пополнения становится равен сумме текущего баланса и суммы пополнения. 

**Локация исправленного места**
https://github.com/IrinaRakova/javaqa-team-diplom-2/blob/f1c42c0b0705c040b1082e6271d25ab023bbfe30/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L90-L104
